### ISSUE TITLE
Naming columns of Grouped Bar chart

### ISSUE THREAD

**Issue by smitpate08** [vega/altair#1227]
Hi,

I am generating  Grouped Bar chart using the below code. I was curious, if there is function available to name the columns of Grouped bar chart. 
Note:  The column "Day_of_the_week' contains 6 levels. I would like to name them as 2=Mon,3=Wed and so on at the top of the chart.
**Code:**
```
alt.Chart(df).mark_bar().encode(
    alt.X('Age:Q',scale=alt.Scale(domain=[25, 60]),bin=alt.Bin(maxbins=50),axis=alt.Axis(title='Age')),
    alt.Y('hours:Q',scale=alt.Scale(domain=[0, 121])),
    color='Day_of_the_week:N'
    ,column='Day_of_the_week'
).properties(width=150,height=200)
```

Thanks in advance,

**Comment by jakevdp** [comment]
The columns should be named by the content of the data itself. The easiest way to change the names is to change the data.

If you can include a full example with the data you're using (or data that is similar), then I can give you more specific advice.

**Comment by jakevdp** [comment]
It's also possible to use the scale argument to change the labels without modifying the data. Again, show a full example and I can help you modify it the way you'd like.

**Comment by smitpate08** [comment]
Thanks, Jake for reply! Currently subset of my dataset  looks like following. Where Days_of_week are 2=Mon, 3= Tues, 4=Wed,5=Thurs,6=Fri. Using the above code, Group Bar chart displays 2,3,4,5,6 on the chart and I would like to replace those numbers with Mon, Tues, Wed,Thurs,Fri or 2=Mon, 3=Tues,4= Wed, 5=Thurs, 6= Fri.

![image](https://user-images.githubusercontent.com/29586703/48982443-8456ee00-f0b0-11e8-8601-684b819db927.png)

**Comment by jakevdp** [comment]
Code is more helpful than a screenshot – otherwise I'll need to transcribe it :smile:

**Comment by jakevdp** [comment]
What I'm looking for is a complete snippet of code that I can copy and paste without modification to produce a plot, see the result you're seeing, and then modify to answer your question. On StackOverflow it's called a [MCVE](https://stackoverflow.com/help/mcve), and including that when asking a coding question on any forum will greatly increase your odds of getting a useful answer.

**Comment by smitpate08** [comment]
Lol completely forgot. Sorry about that. My dataset is similar to  the datset used by user here:[https://www.kaggle.com/hypnobear/absenteeism-at-work-dataset](url), and I am trying to achieve similar results obtained by user at Output line 16 using below code:
```
alt.Chart(df).mark_bar().encode(
    alt.X('Age:Q',scale=alt.Scale(domain=[25, 60]),bin=alt.Bin(maxbins=50),axis=alt.Axis(title='Age')),
    alt.Y('hours:Q',scale=alt.Scale(domain=[0, 121])),
    color='Day_of_the_week:N'
    ,column='Day_of_the_week'
).properties(width=150,height=200)
```

**Comment by jakevdp** [comment]
What code should I copy and paste to create the variable ``df``? (The kaggle notebook refers to a local dataset that I do not have access to)

Sorry to labor this point, but I'm not going to spend my time trying to guess what you're seeing.

**Comment by smitpate08** [comment]
Sorry for that, below is the subset of my dataframe.  I'm plotting Age on X-axis and Absenteeism_time_in_hours on Y-axis, and Day_of_the_week as columns. Please see my below output
**Subset of dataset**
`{'Age': {0: 33, 1: 50, 2: 38, 3: 39, 4: 33}, 'BMI': {0: 30, 1: 31, 2: 31, 3: 24, 4: 30}, 'Social_drinker': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1}, 'Social_smoker': {0: 0, 1: 0, 2: 0, 3: 1, 4: 0}, 'Son': {0: 2, 1: 1, 2: 0, 3: 2, 4: 2}, 'Day_of_the_week': {0: 3, 1: 3, 2: 4, 3: 5, 4: 5}, 'Month_of_absence': {0: 7, 1: 7, 2: 7, 3: 7, 4: 7}, 'Seasons': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1}, 'Service_time': {0: 13, 1: 18, 2: 18, 3: 14, 4: 13}, 'Absenteeism_time_in_hours': {0: 4, 1: 0, 2: 2, 3: 4, 4: 2}, 'Normalized_service': {0: 0.42857142857142855, 1: 0.6071428571428571, 2: 0.6071428571428571, 3: 0.4642857142857143, 4: 0.42857142857142855}}`
**Output:**
![image](https://user-images.githubusercontent.com/29586703/48986200-f85cba80-f0df-11e8-9a57-6cfdc2127aef.png)

**Code for Output**
```
alt.Chart(df).mark_bar().encode(
    alt.X('Age:Q',scale=alt.Scale(domain=[25, 60]),bin=alt.Bin(maxbins=50),axis=alt.Axis(title='Age')),
    alt.Y('hours:Q',scale=alt.Scale(domain=[0, 121])),
    color='Day_of_the_week:N'
    ,column='Day_of_the_week'
).properties(width=150,height=200)
```
In above code, df= my pandas dataframe,Y='Absenteeism_time_in_hours'. I am trying to achieve something similar to what Kaggle user achieved at output line 16 . ie. replacing 0 with Son=0. In my case, it will be 2=Mon, 3=Tues,4= Wed, 5=Thurs,6=Fri.

Hope this give you clear idea!
Thanks again!

**Comment by jakevdp** [comment]
Sorry to belabor this, but it's much better to paste code that defines ``df`` than to describe what it is in words. What I'm asking for is a single block of code, that when copied and pasted **without modification**, will execute and result in the chart you're talking about.

**Comment by smitpate08** [comment]
No worries. My code is looking as below, which when executed generates the plots mention in the above comment

```
alt.Chart(new_project5).mark_bar().encode(
    alt.X('Age:Q',scale=alt.Scale(domain=[25, 60]),bin=alt.Bin(maxbins=50),axis=alt.Axis(title='Age')),
    alt.Y('Absenteeism_time_in_hours:Q',scale=alt.Scale(domain=[0, 121])),
    color='Day_of_the_week:N'
    ,column='Day_of_the_week'
).properties(width=150,height=200)
```
Thanks again for help!

**Comment by mattijn** [comment]
@smitpate08 I think a [reproducible example](https://stackoverflow.com/questions/20109391/how-to-make-good-reproducible-pandas-examples) was meant here.
```python
import pandas as pd
import altair as alt

data_dict = {"Age":{0:33,1:50,2:38,3:39,4:33},
 "Day_of_the_week":{0:3,1:3,2:4,3:5,4:5},
 "DayLabel_of_the_week":{0:"Tue",1:"Tue",2:"Wed",3:"Thu",4:"Thu"},
 "Month_of_absence":{0:7,1:7,2:7,3:7,4:7},
 "Absenteeism_time_in_hours":{0:4,1:0,2:2,3:4,4:2},
}

df = pd.DataFrame.from_dict(data_dict)

alt.Chart(df).mark_bar().encode(
    alt.X('Age:Q',scale=alt.Scale(domain=[25, 60]),bin=alt.Bin(maxbins=5),axis=alt.Axis(title='Age')),
    alt.Y('Absenteeism_time_in_hours:Q',scale=alt.Scale(domain=[0, 8])),
    color='Day_of_the_week:N',
    column='Day_of_the_week'
).properties(width=150,height=200)
```

**Comment by jakevdp** [comment]
Thanks @mattjin. @smitpate08, did that answer your question?

**Comment by smitpate08** [comment]
Thanks @mattijn  and @jakevdp . I was able to get column names at the top of my graph. However, it appears that `sort ` function in `alt.column` is not following correct order specified in `sort` I tried running the same code suggested by @mattijn  in my Juptyer Notebook and I got below output (Days are not in Order specified in `Sort` function). I took subset of my dataset and created the dataframe as suggested by @mattijn, below is my code and Output. I Would like to order my columns based on Day's of the week. i.e Monday -Friday.

**Output after running @mattijn code:**
![image](https://user-images.githubusercontent.com/29586703/49051120-6c689280-f1b4-11e8-9430-e003bf80cd64.png)
```

data_dict = {'Age': {0: 33, 1: 50, 2: 38, 3: 39, 4: 33}, 
              'Day_of_the_week': {0: 3, 1: 3, 2: 4, 3: 5, 4: 5},  
              'Absenteeism_time_in_hours': {0: 4, 1: 0, 2: 2, 3: 4, 4: 2}, 
              'Day_Factor': {0: 'Tuesday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Thursday'},}

df = pd.DataFrame.from_dict(data_dict)

alt.Chart(df).mark_bar().encode(
    alt.X('Age:Q',scale=alt.Scale(domain=[25, 60]),bin=alt.Bin(maxbins=5),axis=alt.Axis(title='Age')),
    alt.Y('Absenteeism_time_in_hours:Q',scale=alt.Scale(domain=[0, 8])),
    color='Day_Factor:N',
    column=alt.Column('Day_Factor', sort=['Monday','Tuesday','Wednesday','Thursday','Friday'])
).properties(width=150,height=200)
```
I am still unsure, if it's NB issue or `Sort` issue.
Thanks again for help!

**Comment by jakevdp** [comment]
That works correctly for me. It's possible you're using an older version of the jupyterlab extension or jupyter notebook extension: in a previous Vega-Lite release, I recall that there was a bug in sorting the column channel. Update your vega extension, and this should work.
