### ISSUE TITLE
JavaScript error with `y='count()'` and `.interactive()`

### ISSUE THREAD

**Issue by wmayner** [vega/altair#1775]
The following MWE results in ```Javascript Error: Cannot read property 'length' of undefined```.

```python
import pandas as pd
import altair as alt

data = pd.DataFrame(dict(x=[1, 2, 3], y=[10, 20, 30]))
alt.Chart(data).mark_bar().encode(
    x='x:N',
    y='count()',
).interactive()
```

It works without `.interactive()`.

**Comment by jakevdp** [comment]
Thanks - this is a known bug in Vega-Lite that was reported a little while ago; see https://github.com/vega/vega-lite/issues/5514 for updates.

The workaround is to use ``y='count(*)'``.
