### ISSUE TITLE
Are there any known bugs with altair.Column(sort)?

### ISSUE THREAD

**Issue by yannxaver** [vega/altair#1973]
**Code**
```
top5_leagues = bvb[bvb['league'].isin(['LaLiga', 'Premier League', 'Bundesliga', 'Serie A', 'Ligue 1'])]

alt.Chart(top5_leagues).mark_bar().encode(
        x='trans_type:N',
        y='sum(fee):Q',
        column=alt.Column('league:N', sort=['LaLiga', 'Premier League', 'Bundesliga', 'Serie A', 'Ligue 1'])
    )
```
**Output**
![visualization-2](https://user-images.githubusercontent.com/17554280/74635000-0e044700-51a0-11ea-9374-74ebe865cbf8.png)

The code is the same as in the example from the docs (which works fine in my environment).

**Example from docs**
```
alt.Chart(source).transform_filter(
    alt.datum.symbol != 'GOOG'
).mark_area().encode(
    x='date:T',
    y='price:Q',
    color='symbol:N',
    row=alt.Row('symbol:N', sort=['MSFT', 'AAPL', 'IBM', 'AMZN'])
).properties(height=50, width=400)
```

I have restarted the kernel and double-checked all expressions but no success so far.
Changing the order of the strings in the array also had no effect.

**Comment by jakevdp** [comment]
Yes, this is a known bug; see https://github.com/altair-viz/altair/issues/1683 and https://github.com/vega/vega-lite/issues/5366
