### ISSUE TITLE
Blank charts due to iris url not working in user guide

### ISSUE THREAD

**Issue by johnyrufus** [vega/altair#2210]
In the user guide: 
https://altair-viz.github.io/user_guide/compound_charts.html#

The iris charts are blank, because the iris url is broken, as 404 is returned when trying to access

https://vega.github.io/vega-datasets/data/iris.json

or when trying to execute the following code

```
import altair as alt
from vega_datasets import data
iris = data.iris.url
print(iris)
import urllib.request, json 
with urllib.request.urlopen(iris) as url:
    data = json.loads(url.read().decode())
    print(data)
```

**Comment by jakevdp** [comment]
There were a number of other changes as well. We'll have to go through the docs and remove references to obsolete data sources.

**Comment by johnyrufus** [comment]
Sure, I can take a look into it if thats okay.
Directly using data.iris() works though.

**Comment by jakevdp** [comment]
> Directly using data.iris() works though.

That will work until the Python ``vega_datasets`` package is updated, at which point iris will be removed following the upstream package.

**Comment by johnyrufus** [comment]
Makes sense. Thanks for the info.

**Comment by joelostblom** [comment]
@johnyrufus I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue is a duplicate so I am closing it, but please feel free to reopen and add a comment if you don't think this is correct.
