### ISSUE TITLE
Some example charts busted in the docs

### ISSUE THREAD

**Issue by palewire** [vega/altair#2217]
https://altair-viz.github.io/user_guide/compound_charts.html#faceted-charts

![Screenshot from 2020-06-22 21-21-31](https://user-images.githubusercontent.com/9993/85360624-70fb4700-b4ce-11ea-852c-b36a18a1a3db.png)

**Comment by jakevdp** [comment]
Thanks! This is due to vega-datasets removing and modifying multiple datasets in their most recent release. Issue is tracked in #2213.

**Comment by joelostblom** [comment]
Closing as duplicate.
