### ISSUE TITLE
Not able to see the full regression line when using alt.UrlData() as the data Source in altair

### ISSUE THREAD

**Issue by rahulsingh7** [vega/altair#2455]
Type here...

---

Please follow these steps to make it more efficient to solve your issue:

- [x] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by rahulsingh7** [comment]
import altair as alt

# pred = pd.read_csv("https://raw.githubusercontent.com/keto08/covid-19/master/COVID19-UK/uk_prediction.csv")
pred = alt.UrlData(url="https://raw.githubusercontent.com/keto08/covid-19/master/COVID19-UK/uk_prediction.csv")
zoom = alt.selection_interval(
    bind='scales',
    on="[mousedown[!event.shiftKey], mouseup] > mousemove",
    translate="[mousedown[!event.shiftKey], mouseup] > mousemove!",
)

selection = alt.selection_interval(
    on="[mousedown[event.shiftKey], mouseup] > mousemove",
    translate="[mousedown[event.shiftKey], mouseup] > mousemove!",
)

chart = alt.Chart(pred,title="Cases").mark_point().encode(
    x=alt.X('cases_actual:Q',title='Actual'),
    y=alt.Y('cases_predicted:Q',title='Predicted'),
    size='population:Q',
    tooltip=[alt.Tooltip('code:N', title="Code"),alt.Tooltip('name:N', title="Name"),alt.Tooltip('dPOP:Q', title="Population Density")]
)

line =chart+ chart.transform_regression(on='cases_predicted',regression='cases_actual',extent=[-3,3]).mark_line(color='red')

line.add_selection(zoom, selection)

here is my code snippet

**Comment by joelostblom** [comment]
This is the same issue as described in https://github.com/altair-viz/altair/issues/2431#issuecomment-806232242. To make sure that CSV data behaves as expected with URL data, you often need to be explicit about the data type. This works for your example:

```python
pred = alt.UrlData(url="https://raw.githubusercontent.com/keto08/covid-19/master/COVID19-UK/uk_prediction.csv",
                   format={'parse': {'cases_predicted': 'number'}})
```

**Comment by rahulsingh7** [comment]
Thanks @joelostblom This works for me....
