### ISSUE TITLE
Improve the syntax for conditions with multiple predicates

### ISSUE THREAD

**Issue by mattijn** [vega/altair#2759]
Questioned in [SO: How to create an altair condition with three or more choices [duplicate]](https://stackoverflow.com/questions/72190774/how-to-create-an-altair-condition-with-three-or-more-choices) and [SO: Combine hover and click selections in Altair](https://stackoverflow.com/questions/66108224/combine-hover-and-click-selections-in-altair) and surfaced in https://github.com/altair-viz/altair/pull/2756

It is currently possible to write a `condition` with single predicate:
```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

base = alt.Chart(cars).mark_tick().encode(x='Miles_per_Gallon:Q')

# condition with single predicate
base.encode(color=alt.condition(
    alt.datum.Origin == 'Europe', 
    alt.value('green'), # when true
    alt.value('red') # when false
    )
)
```
![image](https://user-images.githubusercontent.com/5186265/208255517-e4fba246-a375-4104-8128-3f754f233621.png)

And one can combine multiple selections into a single predicate as is written here: https://altair-viz.github.io/user_guide/interactions.html#composing-multiple-selections

To combine multiple predicates within a single condition one can define a `dict` with a list of conditions as such:
```python
# condition with multiple predicates
color_condition = {
    "condition": [
        {"test": "datum.Origin === 'Europe'", "value": "green"},
        {"test": "datum.Origin === 'Japan'", "value": "blue"},
    ],
    "value": "red",
}
base.encode(
    color=color_condition
)
```
![image](https://user-images.githubusercontent.com/5186265/208255547-a8de940b-fa4c-4545-999e-fc3dd04f06e5.png)

But using an `alt.condition()` this is not possible. 

Maybe something as such should be supported:?
```python
base.encode(color=alt.condition(
    predicate=[
        alt.pred(expr=alt.datum.Origin == "Europe", if_true=alt.value("green")),
        alt.pred(expr=alt.datum.Origin == "Japan", if_true=alt.value("blue")),
    ],
    if_false=alt.value("red")
    )
)
```

**Comment by mattijn** [comment]
@joelostblom do you still have a ideas for this? I like to use this to combine a highlight and click condition. Something quite common, but the approach is not clear yet.

We also can also implement a list of conditions, like `[alt.condition(), alt.condition()]`, or a new `alt.conditions()` (plural) or change the current `alt.condition()` so it by defaults support multiple predicates or do something as `alt.condition() + alt.condition()`.

**Comment by joelostblom** [comment]
Hmm I don't really have a good idea of what is prefereable here, other than in terms of what I would find nice to type myself, which I think would be similar to the last example in your first comment, something like this:

```py
base.encode(
    color=alt.condition([
        (alt.datum.Origin == "Europe", alt.value("green")),
        (alt.datum.Origin == "Japan", alt.value("blue"))
    ],
    alt.value("red")
)
```

**Comment by joelostblom** [comment]
Partly related https://github.com/altair-viz/altair/issues/695

**Comment by mattijn** [comment]
Thanks for commenting @dangotbanned! Very open for suggestions on this. I'm not sure if I understand right, but isn't your suggestion similar to the existing possibility of _parameter composition_, see: https://altair-viz.github.io/user_guide/interactions.html#parameter-composition? In other words, you still have one predicate, and one `if_true` parameter and one `if_false` parameter?

**Comment by dangotbanned** [comment]
> but isn't your suggestion similar to the existing possibility of _parameter composition_, see: https://altair-viz.github.io/user_guide/interactions.html#parameter-composition? @mattijn 

After reading through these again, I think what confused me was the predicate including the "then" clause `if_true`:

```py
predicate=[
    alt.pred(
        expr=alt.datum.Origin == "Europe",
        if_true=alt.value("green")
    ),
    ...
]

```
I hadn't caught that part in the other suggestions, but I would say to me it feels like stretching the definition of what a predicate is.

> In other words, you still have one predicate, and one if_true parameter and one if_false parameter?

Yeah this would be an `AND` reduction of predicates, all sharing the same `if_true`, `if_false`.

**Comment by mattijn** [comment]
It is the first time I see the syntax of `when-then-otherwise`, but upon first sight it feels like a real natural fit for this situation. Nice find!

For this example option 4 seems nice, but I'm not certain if this option can capture other scenarios. Like this Vega-Lite example, https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html, a bar chart with highlighting on hover and selection on click, as was discussed in https://github.com/vega/altair/issues/3301, where we struggle to use current Altair syntax to adapt the VL example.

Really nice to push this forward @dangotbanned!

**Comment by dangotbanned** [comment]
> Really nice to push this forward @dangotbanned!

Thanks appreciate it.

> For this example option 4 seems nice, but I'm not certain if this option can capture other scenarios. Like this Vega-Lite example, [vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html](https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html), a bar chart with highlighting on hover and selection on click, as was discussed in #3301, where we struggle to use current Altair syntax to adapt the VL example.

I'll have a think on it. Adding the other parts here: 
 
## Minimal Repro

`target_stroke` is copied directly from [vega-lite](https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html) - but the rest is possible with existing syntax:
```py
import altair as alt

data = {
    "values": [
        {"a": "A", "b": 28},
        {"a": "B", "b": 55},
        {"a": "C", "b": 43},
        {"a": "D", "b": 91},
        {"a": "E", "b": 81},
        {"a": "F", "b": 53},
        {"a": "G", "b": 19},
        {"a": "H", "b": 87},
        {"a": "I", "b": 52},
    ]
}
highlight = alt.selection_point(name="highlight", on="pointerover")
select = alt.selection_point(name="select")
fill_opacity = alt.condition(select, if_true=alt.value(1), if_false=alt.value(0.3))

target_stroke = {
    "condition": [
        {"param": "select", "empty": False, "value": 2},
        {"param": "highlight", "empty": False, "value": 1},
    ],
    "value": 0,
}

chart_select_highlight = (
    alt.Chart(data)
    .mark_bar(fill="#4C78A8", stroke="black", cursor="pointer")
    .encode(
        x=alt.X("a:O"),
        y=alt.Y("b:Q"),
        fillOpacity=fill_opacity,  # type: ignore
        strokeWidth=target_stroke,
    )
    .add_params(select, highlight)
    .configure(scale={"bandPaddingInner": 0.2})
)
chart_select_highlight
```
![image](https://github.com/vega/altair/assets/125183946/f32aabab-9c77-4412-9c18-e55f9d18c739)

**Comment by mattijn** [comment]
Yes and there your suggestion will come in nicely:

```python
import altair as alt
import polars as pl

df = pl.DataFrame([
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
])

highlight = alt.selection_point(on='mouseover', empty=False)
select = alt.selection_point(on='click', empty=False)

alt.Chart(df).mark_bar(fill="#4C78A8", stroke="black", cursor="pointer").encode(
    x="a:N",
    y="b:Q",
    #fillOpacity=alt.condition(highlight, alt.value(1), alt.value(0.3)),
    fillOpacity=alt.when(highlight).then(alt.value(1)).otherwise(alt.value(0.3))        
    #strokeWidth=alt.condition(select, alt.value(2), alt.value(0))
    strokeWidth=alt.when(select).then(alt.value(2)).when(highlight).then(alt.value(1)).otherwise(alt.value(0)),
).configure_scale(
    bandPaddingInner=0.2
).add_params(highlight, select)
```

**Comment by dangotbanned** [comment]
@mattijn I'm making a start in https://github.com/vega/altair/pull/3427

To piggyback on your example, an important bit to match the original is:

```py
select = alt.selection_point(on="click")

#strokeWidth=alt.condition(select, alt.value(2), alt.value(0))
strokeWidth=alt.condition(select, alt.value(2, empty=True), alt.value(0))
```

Which then becomes:
```py
stroke_width = (
    alt.when(select)
    .then(alt.value(2, empty=False))
    .when(highlight)
    .then(alt.value(1, empty=False))
    .otherwise(alt.value(0))
)
```
Without the `empty=False` in the value, the appearance isn't quite the same as in [vega-lite](https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html):

![image](https://github.com/vega/altair/assets/125183946/53e50283-988d-4890-a1c3-23d35b2dce6c)

**Comment by mattijn** [comment]
I defined the `empty=False` part of the `alt.selection_point`, that is also in line with the Altair API, https://altair-viz.github.io/user_guide/generated/api/altair.selection_point.html.

It seems a bit different than the VL-syntax, but I think this Altair syntax will become the same VL specification upon compilation.

**Comment by joelostblom** [comment]
Intriguing suggestion, thanks @dangotbanned! As Mattijn mention, the `when.then.otherwise` syntax seems like a natural fit for what we are trying to do and the fact that it is used by polars already lends confidence to that it is robust. In terms of syntax, I think it would be quite convenient to have literals treated as `alt.value` and I would enjoy typing something like

```python
color=alt.when(selection).then('green').otherwise('red')
```

over either of these two

```python
color=alt.when(selection).then(alt.value('green')).otherwise(alt.value('red'))
color=alt.condition(selection, alt.value('green'), alt.value('red'))
```

If we go that route, we would have to consider whether we think it is confusing that `alt.value` is not included here, but does need to be included everywhere else in altair. E.g. if I type just `color='green'` then this literal is treated as a column name. We would also need to make sure it is clear that `alt.datum` and `alt.Color` etc can also be passed to `then()`.

Even if we don't include the alt.value literal conversion, I think the syntax is an improvement in terms of allowing multiple predicates which is what this issue is originally about, although the convenience level in that case would be quite similar to the current `alt.condition` option.

**Comment by dangotbanned** [comment]
> We would also need to make sure it is clear that alt.datum and alt.Color etc can also be passed to `then()`.

Thanks @joelostblom, I still have some docs & tests to write before I'm ready for a review. 
If you have any other ideas for tests, let me know and I can add to [what I have so far](https://github.com/dangotbanned/altair/blob/b962c48c773ae999fa69cb3cd191345a01dea9a9/tests/vegalite/v5/test_api.py#L252) 😄

**Comment by dangotbanned** [comment]
- #3427 

Just checking in again over here, as I'm planning to move the PR out of draft soon. 

@mattijn it would be great to hear your thoughts on https://github.com/vega/altair/pull/3427#discussion_r1626275778 as I could drop this support if you agree, or you may have a better solution in mind?
