### ISSUE TITLE
Adapting Vega-Lite example "Bar Chart with Highlighting on Hover and Selection on Click"

### ISSUE THREAD

**Issue by ChristopherDavisUCI** [vega/altair#3301]
This is a follow-up to https://github.com/altair-viz/altair/discussions/3295

@mattijn Thanks for linking this [Vega-Lite example](https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html) which I didn't know existed.

In that example, `condition` seems to take an array, but I don't see any mention of that as an option in the [condition documentation](https://vega.github.io/vega-lite/docs/condition.html), nor does our code seem to allow using lists for a condition, as far as I can tell:
https://github.com/altair-viz/altair/blob/d38409f8f50282d09507f90e490e65c0f0247b25/altair/vegalite/v5/api.py#L787-L796

Does that seem accurate to you?  How would you suggest we approach that?

Needless to say, I'm happy for comments from anyone!

**Comment by mattijn** [comment]
Hi @ChristopherDavisUCI! This was discussed in this issue: https://github.com/altair-viz/altair/issues/2759. 

It would be nice if we can extend and improve Altair by allowing for multiple predicates as part of a condition.

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn!  Do you know anywhere that this array functionality is described on the Vega-Lite side?

**Comment by mattijn** [comment]
Is this page of help: https://vega.github.io/vega-lite/docs/condition.html?

**Comment by ChristopherDavisUCI** [comment]
Not that I know of?  I've tried searching that page for the word "array", and have skimmed through the examples and haven't seen anything that looks similar to the list/array usage in the [Bar Chart example](https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html), but I could definitely believe that it's there and I'm missing it...

**Comment by mattijn** [comment]
You are right, it's not really clear from there.
Maybe a bit from the Vega docs at this page: https://vega.github.io/vega/docs/marks/#encode. Scroll down to the section on _Production Rules_
