### ISSUE TITLE
alt.Scale issue

### ISSUE THREAD

**Issue by Amarounek** [vega/altair#3406]
### What happened?

Hello

I  am experiencing a bug for mark_bar when I am using alt.Scale(domain=[200, 2500]) for Y axis with scale=alt.Scale(scheme='reds') on Alt.colors (Not only on this snippet of course). The bars are still trying to reach zero...

My snippet:

```
from vega_datasets import data
source = data.barley()

con_dry_day = alt.Chart(source).mark_bar(opacity=0.65).encode(
    alt.X("year:O", axis=alt.Axis(titlePadding=10), title="Year", scale=alt.Scale(nice=False)),
    alt.Y("yield:Q", axis=alt.Axis(titlePadding=10), title="Every 15th day of dry periods", scale=alt.Scale(domain=[200, 2500])),
    color=alt.Color("yield:Q", scale=alt.Scale(scheme='reds'), legend=None)
).properties(width=1000, height=350)
con_dry_day
```
Thanks!

![image](https://github.com/vega/altair/assets/36733547/9520c37d-1e02-4031-adfd-ad624ee63384)

### What would you like to happen instead?

Obviously, I would like to have bars from a minimum limit of the scale to be able to visualize clearly some difference (more dramatic figures)

### Which version of Altair are you using?

Altair version: 5.2.0

**Comment by jonmmease** [comment]
Hi @Amarounek, I think the scale itself is acting the way you would expect here, but the marks are being draw outside of the axes. This is controlled on a per-mark bases using the `clip` property. Vega-Lite (and therefore Vega-Altair) defaults to clip=False, but if you set `clip=True`, this is what you get:

```python
from vega_datasets import data
import altair as alt
source = data.barley()

con_dry_day = alt.Chart(source).mark_bar(opacity=0.65, clip=True).encode(
    alt.X("year:O", axis=alt.Axis(titlePadding=10), title="Year", scale=alt.Scale(nice=False)),
    alt.Y("yield:Q", axis=alt.Axis(titlePadding=10), title="Every 15th day of dry periods", scale=alt.Scale(domain=[200, 2500])),
    color=alt.Color("yield:Q", scale=alt.Scale(scheme='reds'), legend=None)
).properties(width=1000, height=350)
con_dry_day
```
![visualization](https://github.com/vega/altair/assets/15064365/5865cf2a-aaa1-44c8-ae4e-4cdfe49a018c)

**Comment by Amarounek** [comment]
@jonmmease Great thanks!!!
