### ISSUE TITLE
Escaping special chars in col names with a single backslash raises warnings

### ISSUE THREAD

**Issue by joelostblom** [vega/altair#3410]
### What happened?

When I run [the example with special chracters from the docs](https://altair-viz.github.io/user_guide/encodings/index.html#escaping-special-characters-in-column-names), I see a bunch of warnings:

![image](https://github.com/vega/altair/assets/4560057/df3eda06-5255-4216-b688-1263e182deba)

### What would you like to happen instead?

Replacing the single `\` with double `\\` fixes the issue. We could just update the docs, but before doing so I'm curious if anyone knows if something changed (in altair/ipython/python) that makes this warning visible now and if others see it or it is something with my local env.

### Which version of Altair are you using?

main

**Comment by jonmmease** [comment]
Rather than using double backslashes, I think using raw strings (those prefixed by `r`, e.g. `r'col\.period'`) would fix the issue by bypassing Pythons own escaping logic. And I think this makes things a little easier to reason about.
