### ISSUE TITLE
Some online dependency's Cloudflare SSL certificate is expired.

### ISSUE THREAD

**Issue by jhyoo1982** [vega/altair#3412]
### What happened?

Altair Examples are not shown.

<img width="1251" alt="Screenshot 2024-05-02 at 1 49 28 PM" src="https://github.com/vega/altair/assets/876125/fdcb7821-7a82-4599-9555-f683ae6e7b34">

I also tested in on my jupyter notebook and not working because of an error:
`Error loading script: https://cdn.jsdelivr.net/npm/vega@5?noext
`
<img width="649" alt="Screenshot 2024-05-02 at 2 06 24 PM" src="https://github.com/vega/altair/assets/876125/c06870de-c79e-4541-a849-aa0df0d8ceb0">

in JupyterLab cell output,

`GET https://cdn.jsdelivr.net/npm/vega@5?noext net::ERR_CERT_DATE_INVALID`
in Chrome's developer console.

~~ssl certificate is expired a few hours ago I think.~~
actually it is expired a few years ago. then I don't know why this is happening all of sudden?
<img width="1369" alt="Screenshot 2024-05-02 at 1 48 14 PM" src="https://github.com/vega/altair/assets/876125/5db74440-6c9b-4940-a84f-95c7dd071289">

I checked my system time is correct. I also checked this via my phone which syncs time to mobile carrier which is very exact.

### What would you like to happen instead?
It should show examples.

### Which version of Altair are you using?

5.3.0

**Comment by jhyoo1982** [comment]
Okay this is not Altair's issue.
https://community.cloudflare.com/t/jsdelivr-expired-certificate-may-2024/650543/4

**Comment by mattijn** [comment]
Follow https://github.com/jsdelivr/jsdelivr/issues/18565 updates.
