### ISSUE TITLE
xOffset seems to have no effect

### ISSUE THREAD

**Issue by mahadi** [vega/altair#3415]
### What happened?

In the example in https://github.com/ChristopherDavisUCI/altair/commit/af0c3b4c1d27c366fb66fb6743aa15d5d30a56ce i want to test the effect of the xOffset attribute.

Example (copied):

Jitter Chart
------------
In this chart, we encode the ``Cylinders`` column from the ``cars`` dataset in the ``y``-channel.  Because most cars (all but seven) in this dataset have 4, 6, or 8 cylinders, the default presentation of this data would show most of the data concentrated on three horizontal lines.  Furthermore, in that default presentation, it would be difficult to gauge the relative frequencies with which different values occur (because there would be so much overlap).  To compensate for this, we use the ``yOffset`` channel to incorporate a random offset (jittering).  This is adapted from a corresponding Vega-Lite Example:
`Dot Plot with Jittering <https://vega.github.io/vega-lite/examples/point_offset_random.html>`_.

```py
# category: scatter plots
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_point().encode(
    x='Horsepower:Q',
    y='Cylinders:O',
    yOffset='randomCalc:Q'
).transform_calculate(
    randomCalc='random()'
).properties(
    height=alt.Step(50)
)
```
The yOffset works as expected.
![visualization](https://github.com/vega/altair/assets/124618/0de78992-4201-4d3c-93e2-10c2f076c2bb)

But when i change the yOffset to xOffset there is no effect.

```py
alt.Chart(source).mark_point().encode(
    x='Horsepower:Q',
    y='Cylinders:O',
    xOffset='randomCalc:Q'
).transform_calculate(
    randomCalc='random()'
).properties(
    height=alt.Step(50)
)
```
![visualization_xOffset](https://github.com/vega/altair/assets/124618/65f52463-8af6-4adb-b0c6-93408a034712)

If i compare the output with the deactivated `xOffset` there is no difference:

```py
alt.Chart(source).mark_point().encode(
    x='Horsepower:Q',
    y='Cylinders:O',
    # xOffset='randomCalc:Q'
).transform_calculate(
    randomCalc='random()'
).properties(
    height=alt.Step(50)
)
```
![visualization_no_xOffset](https://github.com/vega/altair/assets/124618/c91cce93-088d-4a6f-98d0-6a093e516d9e)

So it seems that the xOffset does not have any effect.

### What would you like to happen instead?

I would expect that the x coordinates of the points receive the same jitter as the y axis.
I also tried to scale the xOffset, but not effect.

### Which version of Altair are you using?

5.3.0

**Comment by mattijn** [comment]
The `x` channel is here encoded as a quantitative type (`:Q`) for field `Horsepower`. 

An offset on `x` (`xOffset`) or `y` (`yOffset`) can only be applied if that field type is nominal or ordinal.

**Comment by mahadi** [comment]
I tried with `x='Horsepower:O'` and it works. Thank you for that hint.

I didnt know about that restriction. Is this documented somewhere?
At least from my understanding it should be possible to calculate an x offset also for a quantitative type... What i am missing here?

**Comment by mattijn** [comment]
I've no idea how an `xOffset` on a quantitative `x` axis would look like. Do you have a reference how that would look like in your understanding?

Regarding docs, there is the API docs on this encoding channel: https://altair-viz.github.io/user_guide/generated/channels/altair.XOffset.html

I'm sure a PR to improve this within the Vega-Lite repository would be much appreciated (as it is the source of the Altair API pages).

Otherwise, you could write a section on this at this Altair page: https://altair-viz.github.io/user_guide/encodings/channels.html

**Comment by mahadi** [comment]
My use case is: I have a bunch of values over a certain ambient temperature range. Typicaly data is collect at e.g. -30°C, 0°C, 25°C and 60°C. But depending on the use case i can also have data at -5, -10, -20 °C. So when i plot the dots, having the ambient temperature on the x-axis, i have them as "lines" of points. My target is to simulate a plot similar to seaborn's swarmplot.

In https://altair-viz.github.io/gallery/strip_plot_jitter.html#gallery-strip-plot-jitter the jitter would be helpful, but without the need to categorize the data as the x-axis is continuous.

While thinking about this i could also achieve this by creating a new column in my data frame and jitter the data there...
For sure i am aware of boxplots, but the outliers are interesting to me and altair's interactivity is pretty helpful when i want to analyze single points by clicking directly on them and getting their data source.
