### ISSUE TITLE
Changes axis titles dynamically based on the selected parameter value

### ISSUE THREAD

**Issue by liquidcarbon** [vega/altair#3417]
### What happened?

The docs state:

![image](https://github.com/vega/altair/assets/47034358/f807118a-559b-4525-88f8-7b383d1da884)

This appears to already work in VegaLite (see below).  But Altair would say `SchemaValidationError: '{'expr': 'param_43'}' is an invalid value for `title`. Valid values are of type 'string', 'array', or 'null'.`

```
import numpy as np
import pandas as pd


rand = np.random.RandomState(42)
df = pd.DataFrame({
    'xval': range(5),
    'yval': rand.randn(5).cumsum().astype(int)
})

bind_range = alt.binding_range(min=100, max=300, name='Slider value:  ')
param_width = alt.param(bind=bind_range)

# Examples of how to write both js and python expressions
param_color_js_expr = alt.param(expr=f"{param_width.name} < 200 ? 'red' : 'black'")
param_color_py_expr = alt.param(expr=alt.expr.if_(param_width < 200, 'red', 'black'))

chart = alt.Chart(df).mark_point().encode(
    alt.X('xval').axis(titleColor=param_color_js_expr),
    alt.Y('yval').axis(titleColor=param_color_py_expr)
    # alt.Y('yval').axis(title=param_color_py_expr)  # SchemaValidationError
).add_params(
    param_width,
    param_color_js_expr,
    param_color_py_expr
)
chart
```

### What would you like to happen instead?

[VegaLite](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAjAHZKABkoArCGwB2IADQgoagGY0yaUEgAeNCEZBkATjQAmAdXv00krYKRM4ggGJrMaCAAMkiYbJogHl6+-gDKNABecK4ALFqYdIJwfqqY8UmuAGwAvu7kcKp2llHeOQHoIWERNTG5+cmokmJaOEh2djSqhp0ATOmZ2XGJHTKlIBmYWZZIqrBs1oEQmEjWAVq6-oGN4ftTBagjclpsuroQcPVdxXN2oSiooKpICB0gr9v8MR2ACcYiQckKwKYKSgAA5JIU5NI5MD4Z44FARnARrdgaiQC83vdMBYPn83oCQWCIVCYfDEcjUZJ0Zjsbj8agANqgEzEJCCNBXEAATz5AtQclKPLFri0ov5gqlIF5CoucplnSVKvFAGZ1aqRlqNWkRRrDRpparuqaDcUALpzCo6AZDSwmZZmUmgBZZADCbEE60scBMOA26F61m+AH0UnICXN9N4quhtRFMMKcL8AI4MFYLUI0UgEuUe8yWH0dUAhsOBSMxlKSBP7GjJwLygXpTM5vO5OiF4vPLTIawAawr3brbEGATm9YQpO5ICYgxToEGOAY9RAUaGyWHpjQOrkQoQg1cJ60Xx+gViwjscGsAAIxQw4Kgn0+SyBr7959GdWBEtq1DcMQH-QCnwAHifS45CfAB+J8AHJrDgOxkKfD9kKYDwoFHZCIl-OsdgbeMlRrMCaF0AAKGiIOBaDYJPABKDRUPQ5D2NwpB8OQliiO+P9SIQWMm3tYogA)

![VegaAxisTitles](https://github.com/vega/altair/assets/47034358/61e02776-faf1-471b-a9e4-90ede4286947)

### Which version of Altair are you using?

5.3.0

**Comment by binste** [comment]
Thanks for opening this issue. The Vega-Lite schema does not accept expressions for titles either, you can see this also in the Vega Editor when hovering over it:

![image](https://github.com/vega/vega-lite/assets/23366411/a81629a1-5281-4f8f-b5d4-eef7f92fc609)

However, the chart still does what you want it to do because the underlying Vega grammar does support it and Vega-Lite just passes the string through despite the error. Altair is to a large part auto-generated based on this Vega-Lite schema and hence, this first needs to be fixed in Vega-Lite before it's available in Altair. I'm not aware of any way to circumvent this until that's the case :)

**Comment by liquidcarbon** [comment]
Oh that's interesting, I did not notice the red squiggle in Vega editor!

Well...to match Vega behavior, would you perhaps let it pass in python with a warning instead of a hard error?

**Comment by binste** [comment]
I'm worried that this might be surprising for other users. Altair always made the promise that it produces JSON which is fully compatible with the Vega-Lite schema. There might be applications which rely on this. Also, there are other attributes which have the same behaviour and ideally we just clean this up in Vega-Lite directly.

In the meantime, you can also display Altair charts without any validation at all. Does that help?

```python
spec = chart.to_dict(validate=False)
from IPython.display import display, HTML
renderer = alt.renderers.get()
display(HTML(renderer(spec)["text/html"]))
```

It's more verbose but you could wrap it into a function if you need it often.

**Comment by binste** [comment]
Great! I'm closing this issue as we already have the VL issue.
