### ISSUE TITLE
Supporting partial highlighting in text or title

### ISSUE THREAD

**Issue by chenyulue** [vega/altair#3425]
### What is your suggestion?

Sometimes I want to highlight some words in the title, subtitle or annotation text, such as the subtitle in the following chart, where I highlight the "Players of color is declining" with the color of the corresponding line.

![newplot](https://github.com/vega/altair/assets/44137770/61ce8a89-af2b-4c1f-bbbd-ac9968b70abb)

At present, the color property of text or title seems only to support the coloring of the entire text. I can't find any simple way to achive this. The above chart is created by plotly, which supports some of html tag in text, such as `span` which I use to highlight the partial text.

I wonder whether there are any ways to do it. If not, can altlair support this feature?

### Have you considered any alternative solutions?

I have considered to use multiple `mark_text` to achive this in the annotation text, but it's too cumbersome; this workaround still can't highlight partial text in the title or subtitle.

**Comment by binste** [comment]
I'd also find that a cool feature! This is something that would first need to be implemented in Vega-Lite before it comes to Vega-Altair so I'm closing this in favor of the other issue you opened https://github.com/vega/vega-lite/issues/9357
