### ISSUE TITLE
Add additional `ruff` rules to `pyproject.toml`

### ISSUE THREAD

**Issue by dangotbanned** [vega/altair#3430]
Following a comment in [#3420 review](https://github.com/vega/altair/pull/3420#discussion_r1610436425), I've collected a range of `ruff` rules, to propose adopting in `altair`. 

This is an opinionated list, with a focus on rules providing an autofix (`ruff check . --fix`) - to limit any extra work removing warnings.

I think the `ruff` docs do a great job explaining each rule, so I've kept my additional notes brief. Strongly recommend checking out rules marked with a 🛠️ for examples of the change they would make.

Also, if accepted, I would suggest introducing any new rules close to a new release - since this would very likely create a large diff, especially if all of these were added at once.

## [flake8-simplify (SIM)](https://docs.astral.sh/ruff/rules/#flake8-simplify-sim)
- Majority have autofixes
- First mentioned in [#3420 review](https://github.com/vega/altair/pull/3420#discussion_r1610436425)

## [pydocstyle (D)](https://docs.astral.sh/ruff/rules/#pydocstyle-d)
  - Majority have autofixes
  - I haven't come across any `altair` specific doc conventions
  - A starting point could be the config below and then tweaking `DXXX` rules from there
  - See [docstring-formatting](https://docs.astral.sh/ruff/formatter/#docstring-formatting) for sample output

```toml
[tool.ruff.format]
docstring-code-format=true
docstring-code-line-length=72

[tool.ruff.lint]
pycodestyle={ max-doc-length=88 }
pydocstyle={ convention="numpy" }
```

## [pyupgrade (UP)](https://docs.astral.sh/ruff/rules/#pyupgrade-up)
- All have autofixes and respect `tool.ruff.target-version`
- Really helpful considering [altair 1.0.0](https://pypi.org/project/altair/1.0.0/#description) targeted `python>=2.7,<3.6`
- When paired with [FA100](https://docs.astral.sh/ruff/rules/future-rewritable-type-annotation/#future-rewritable-type-annotation-fa100), the autofixes can help improve readability of annotations - some of which are particularly verbose on `python<3.9`.

## [flake8-type-checking (TCH)](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch)
- Majority have autofixes
- Related to [#3405](https://github.com/vega/altair/pull/3405) @binste
- Also relates to `UP`, `FA100`

## [flake8-errmsg (EM)](https://docs.astral.sh/ruff/rules/#flake8-errmsg-em)
- All have autofixes

## [flake8-pie (PIE)](https://docs.astral.sh/ruff/rules/#flake8-pie-pie)
- All have autofixes, except [PIE796](https://docs.astral.sh/ruff/rules/non-unique-enums/)
- Found only a [single use](https://github.com/vega/altair/blob/18a2c3c237014591d172284560546a2f0ac1a883/altair/utils/_dfi_types.py#L11) of `enum` anyway

## [flake-8-use-pathlib (PTH)](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth)
- No autofixes, but most do improve readability
- First mentioned in [#3426 commit](https://github.com/vega/altair/pull/3426/commits/8a9d59389df6d1a270f389346cbe2dbabf2e67ad)

## Misc
- [static-join-to-f-string (FLY002)](https://docs.astral.sh/ruff/rules/static-join-to-f-string/)
- [Ruff-specific rules (RUF)](https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf)

## Library-specific
These seem like a good fit, based on the [current dependencies](https://github.com/vega/altair/blob/18a2c3c237014591d172284560546a2f0ac1a883/pyproject.toml) however I haven't used them before - unlike all other suggestions:
- [NumPy-specific rules (NPY)](https://docs.astral.sh/ruff/rules/#numpy-specific-rules-npy)
- [pandas-vet (PD)](https://docs.astral.sh/ruff/rules/#pandas-vet-pd)
- [flake8-pytest-style (PT)](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt)

## [Preview](https://docs.astral.sh/ruff/preview/)
These mostly require the opt-in preview mode, with varying degrees of autofixes. 

- [pylint (PLC, E, R, W)](https://docs.astral.sh/ruff/rules/#pylint-pl)
- [refurb (FURB)](https://docs.astral.sh/ruff/rules/#refurb-furb)

**Comment by binste** [comment]
That's a great compilation, thank you! :) I'm all in favour of adding more consistency to the code base for better readability and less time spent in code reviews on style.

I've went through most of the rules and they sound reasonable to me. I'm not aware of larger refactorings right now so maybe it's as good a time as any to introduce the rules. I'd suggest a PR with only auto-fixable rules so we don't have to review line by line and can trust ruff. After that is merged, another PR with rules which require discussions and tweaking such as pydocstyle.

@dangotbanned Would you be open to submitting such a PR? Thanks again for your work recently!

**Comment by dangotbanned** [comment]
> @dangotbanned Would you be open to submitting such a PR? Thanks again for your work recently!

Thank you @binste 

Yeah I'm happy to make a start on it.

The two PRs I have open currently, #3426 #3427, might need some work post-merge of this. 
Just noting that now, so this comes up in review.

**Comment by dangotbanned** [comment]
@binste I think #3431 is ready for review. Just finished up a lot of manual work to get [pathlib](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth) rules passing. 

The remaining tasks require more discussion, but would be good to get these merged
