### ISSUE TITLE
Timeunit week

### ISSUE THREAD

**Issue by aleixalcacer** [vega/altair#3432]
### What is your suggestion?

Is it possible to implement a TimeUnit for weeks in a year? I didn't find information on this feature on docs, and I believe it would be valuable for `altair` users.

Vega supports it: https://vega.github.io/vega-lite/docs/timeunit.html

**Comment by mattijn** [comment]
Closing with the answer is better: https://altair-viz.github.io/user_guide/transform/timeunit.html. Thanks!

**Comment by aleixalcacer** [comment]
> Closing with the answer is better: https://altair-viz.github.io/user_guide/transform/timeunit.html. Thanks!

Sorry, you are right :)

Maybe it would be interesting to add it to the documentation. It works now, but it is not documented.

**Comment by mattijn** [comment]
Would you be willing to share your solution?
