### ISSUE TITLE
Some examples in docs can't work 

### ISSUE THREAD

**Issue by wybert** [vega/altair#3468]
### What happened?

Some examples in docs [https://altair-viz.github.io/user_guide/data.html](https://altair-viz.github.io/user_guide/data.html) can't work neither online nor local when running the code. See below,

<img width="844" alt="image" src="https://github.com/vega/altair/assets/5254627/a37954bd-5d1f-428c-b451-fcd56afb424e">

### What would you like to happen instead?

Work as expected

### Which version of Altair are you using?

5.3.0

**Comment by joelostblom** [comment]
I believe that is working as expected since the dataframe describes the shapes of the Altair logo. Could you elaborate on how your expectation is different from the current output?

**Comment by wybert** [comment]
I see. I thought it will show a map.
