### ISSUE TITLE
`_EncodingMixin.encode` types defined too narrow

### ISSUE THREAD

**Issue by dangotbanned** [vega/altair#3552]
### What happened?

Noticed this regression since https://github.com/vega/altair/pull/3515 while writing the test for https://github.com/vega/altair/pull/3394#issuecomment-2302995453

![image](https://github.com/user-attachments/assets/b2dac416-bd75-48e7-9d6a-b8f69f120f2b)

# Minimal repro
```py
import altair as alt

alt.Chart().encode(color=alt.when(x=1).then(alt.value("grey")))
```

### What would you like to happen instead?

The types @binste and I defined for `EncodeKwds` were too strict and didn't account for `alt.(condition|when)`. 

The simplest fix would be to add `SchemaBase` to each annotation - as that is what `Then` falls into

### Which version of Altair are you using?

https://github.com/vega/altair/commit/c984002d500f42ea14ba38e087f0c746af5e3722

**Comment by binste** [comment]
Nice catch!

Looking a bit into it, I think it's not a regression as `color` (and other channels) were not typed with `SchemaBase` before as well. It worked/still works for `alt.condition` if it returns a `dict`, which it does in some cases, and not `SchemaBase`.

Adding `SchemaBase` as a hint sounds pragmatic to me. Feel free to go for it! I'm mostly without reception the next 2 days but can check in again on Sunday. If you want to merge this and release before that, that's ok with me. We can narrow the type hint again in the future if we have a better idea.

**Comment by dangotbanned** [comment]
> Nice catch!
> 
> Looking a bit into it, I think it's not a regression as `color` (and other channels) were not typed with `SchemaBase` before as well. It worked/still works for `alt.condition` if it returns a `dict`, which it does in some cases, and not `SchemaBase`.

Huh you're right @binste. 
I spent so much time with the `@overload`(s) on `alt.(condition|when)` that I was sure `SchemaBase` was here before.

> Adding `SchemaBase` as a hint sounds pragmatic to me. Feel free to go for it! I'm mostly without reception the next 2 days but can check in again on Sunday. If you want to merge this and release before that, that's ok with me. We can narrow the type hint again in the future if we have a better idea.

There are a few things we can try (will update tomorrow with some alternatives)
but I think we risk making `.encode()` too noisy in terms of annotations *again*

**Comment by binste** [comment]
* col_2: Agree with you that we don't want to promote alt.Then directly
* col_3: No preference if we have `Map | SchemaBase` directly in the type hints or use an alias.
* col_4 and col_5: If I understand it correctly, all `SchemaBase` would pass as `SchemaLike`. Hence, if we use `SchemaLike`, we are as permissive as if we would just use `SchemaBase` directly, even a bit more. As `SchemaBase` is already too broad of a type hint, I'm not sure if we get any mileage out of the protocol.

For the above reasons, I currently prefer col_1. It solves the type errors, although the hints will be too broad. But I don't see a simple way of fixing that without changing the return types of `alt.condition` which sounds like a larger issue. Not sure if that's worth tackling right now. What do you think?

**Comment by dangotbanned** [comment]
Really appreciate you taking the time to think this over @binste 

> col_4 and col_5: If I understand it correctly, all `SchemaBase` would pass as `SchemaLike`. 
> Hence, if we use `SchemaLike`, we are as permissive as if we would just use `SchemaBase` directly, even a bit more.
> As `SchemaBase` is already too broad of a type hint, I'm not sure if we get any mileage out of the protocol.

I've revised the original idea a little and added some examples over on #3567 to demo usage.


So far, that covers what `mypy|pyright` think - but the other component is the runtime checking.

---

With `@runtime_checkable`, you are right that any `SchemaBase` will [still pass](https://docs.python.org/3/library/typing.html#typing.runtime_checkable).
However, we do *already* work around this for other protocols e.g. for `SupportsGeoInterface`

<details><summary><code>alt.utils.data.to_values</code></summary>
<p>

https://github.com/vega/altair/blob/5207768b6e533c0509218376942309d1c7bac22f/altair/utils/data.py#L311-L332

</p>
</details> 

It is mostly just thinking about which might need to take **priority** for a **particular** use. 

Reusing the `_to_dict` example from before, `SchemaBase` already takes priority.
`SchemaLike` would be replacing the `hasattr(obj, "to_dict")` branch - or both could be merged - since all we need is the method found in the protocol.

<details><summary><code>tools.schemapi.schemapi._todict</code></summary>
<p>

https://github.com/vega/altair/blob/5207768b6e533c0509218376942309d1c7bac22f/tools/schemapi/schemapi.py#L501-L536

</p>
</details>

**Comment by binste** [comment]
The draft PR is very helpful! Trying to summarise/reword it for myself:
* `Then` should not inherit from `SchemaBase` as it muddies autocompletion
* We need a type hint which lets a `SchemaBase` pass due to `alt.condition` and `alt.when().then().otherwise(). Can be `SchemaBase` or a protocol
* It's unclear to me when, as a developer, I'd use `SchemaLike`. If I understand it correctly, we mainly introduce it now to make these types work.
* Purpose:
  * Fix type errors users might get right now, keeping types as narrow as possible so they are more useful
  * Improving UX: keep/improve autocompletion + provide a good visual indication that we mean conditions can be passed

What do you think about 
```python
@runtime_checkable
class Condition(Protocol):
   """We use this protocol to signal to a user that they can pass any condition created by either `alt.condition` or `alt.when`.

   Other SchemaBase instances will pass as `Condition` as well and so for type checkers it won't matter but using this protocol when only conditions are expected at least gives a better visual indication to users.
   """
    _schema: ClassVar[_SchemaLikeDict] = {"type": "object"}

    def to_dict(self, *args, **kwds) -> Any: ...


def chart_encode(
   col_7: Optional[str | Color | Condition | Map | ColorDatum | ColorValue] = Undefined,
)
```
`Condition` is not yet used anywhere in the codebase and it makes it clearer what we intend to do with the protocol. Thoughts?

**Comment by binste** [comment]
I thought it was ok to just use `Map` to cover `otherwise` and `alt.condition` (in the usual cases) but agree that it's even better to also have it in `Condition` -> You're `TypeAlias` idea sounds great!

**Comment by dangotbanned** [comment]
> I thought it was ok to just use `Map` to cover `otherwise` and `alt.condition` (in the usual cases) but agree that it's even better to also have it in `Condition` -> You're `TypeAlias` idea sounds great!

Thanks happy to hear it @binste 

I'll loop back to this but definitely want to have this fixed for `v5.5.0`.
For reference on the name of this alias, these were why I'd be leaning *away* from `Condition`:

Using `Into...` would align with `IntoExpression`:
https://github.com/vega/altair/blob/df14929075b45233126f4cfe579c139e0b7f0559/altair/expr/core.py#L240

- `narwhals` has some helpful ones like this https://github.com/narwhals-dev/narwhals/blob/5f91aa17c6cd9274851d219f4b50abe12c0fdfeb/narwhals/typing.py#L35-L53
- So does `polars` w/ https://github.com/pola-rs/polars/blob/17cf78ff6e5e37016e43c1d4b426a90d4cfbfe29/py-polars/polars/_typing.py#L88-L92

Maybe this annotation represents:
  > *"anything that can convert into a conditional encoding/property"*

---

None of these directly collide with `Condition`, but there is somewhat of a hierarchy to components of conditions defined:
https://github.com/vega/altair/blob/df14929075b45233126f4cfe579c139e0b7f0559/altair/vegalite/v5/api.py#L629-L660
https://github.com/vega/altair/blob/df14929075b45233126f4cfe579c139e0b7f0559/altair/vegalite/v5/api.py#L523-L537

**Comment by binste** [comment]
I don't have a strong preference here. `IntoCondition` is also fine. It could also be a type alias which we do not expose externally and then we should just aim for what provides the best UX and can always change it later if we want to broaden it's scope.

**Comment by dangotbanned** [comment]
Will be moving onto this issue next, just noting here another [internal typing issue](https://github.com/vega/altair/blob/a171ce8cb2f0b0cb0c944ddbd0c0623282570c0c/altair/vegalite/v5/api.py#L1148) for `when-then-otherwise` that I'll attempt to fix in that PR:

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/d9473d18-a5bf-474f-838c-c5a9da9db74c)

</details>

I'm only getting this warning after correctly enabling support for `__extra_items__` in https://github.com/vega/altair/pull/3585.

I used a different benefit of the feature in [fix: Support hyphenated keys in `TypedDict`(s) (`0bdfa72` (#3536))](https://github.com/vega/altair/pull/3536/commits/0bdfa72470551b2bc39e4adc76b7e989ccdf259b)
