### ISSUE TITLE
configure_axisX(title='foo') removes x-axis title

### ISSUE THREAD

**Issue by MarcoGorelli** [vega/altair#3582]
### What happened?

I ran
```python
alt.Chart(pl.DataFrame({'a':[1,2,3], 'b':[4,5,6]})).mark_line().encode(x='a', y='b').configure_axisX(title='foo')
```
and got

![image](https://github.com/user-attachments/assets/cfe6ec90-983a-4c72-b3be-b4e7daa21c11)

### What would you like to happen instead?

![image](https://github.com/user-attachments/assets/e95fd36f-e722-4693-bce1-a781bebc82fc)

### Which version of Altair are you using?

5.4.1

**Comment by dangotbanned** [comment]
@MarcoGorelli to get the result you're after, the `title` needs to be set as a property on the `X` encoding

```py
# NOTE: Original
# chart = (
#     alt.Chart(pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]}))
#     .mark_line()
#     .encode(x="a", y="b")
#     .configure_axisX(title="foo")
# )
# NOTE: Fixed
chart = (
    alt.Chart(pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]}))
    .mark_line()
    .encode(x=alt.X("a").title("foo"), y="b")
)
chart

```

![image](https://github.com/user-attachments/assets/c6379326-f52f-45c2-9a74-ccc6f1564df5)

You can check where this ends up in the spec with `Chart.to_dict()`:

<details>
<summary>Original</summary>

```py
{'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300},
  'axisX': {'title': 'foo'}}, 												# <-----------------------
 'data': {'name': 'data-be85e675f9b8f0270cc9ebf085a7356c'},
 'mark': {'type': 'line'},
 'encoding': {'x': {'field': 'a', 'type': 'quantitative'},
  'y': {'field': 'b', 'type': 'quantitative'}},
 '$schema': 'https://vega.github.io/schema/vega-lite/v5.20.1.json',
 'datasets': {'data-be85e675f9b8f0270cc9ebf085a7356c': [{'a': 1, 'b': 4},
   {'a': 2, 'b': 5},
   {'a': 3, 'b': 6}]}}
```

</details>

<details>
<summary>Fixed</summary>

```py
{'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}},
 'data': {'name': 'data-be85e675f9b8f0270cc9ebf085a7356c'},
 'mark': {'type': 'line'},
 'encoding': {'x': {'field': 'a', 'title': 'foo', 'type': 'quantitative'}, # <-----------------------
  'y': {'field': 'b', 'type': 'quantitative'}},
 '$schema': 'https://vega.github.io/schema/vega-lite/v5.20.1.json',
 'datasets': {'data-be85e675f9b8f0270cc9ebf085a7356c': [{'a': 1, 'b': 4},
   {'a': 2, 'b': 5},
   {'a': 3, 'b': 6}]}}
```

</details>

**Comment by MarcoGorelli** [comment]
ah, thanks @dangotbanned ! 🙏 closing then

**Comment by dangotbanned** [comment]
> I also got a question, related to this. How would I call this within the polars plot directive?
> 
> Given
> 
> ```python
> import polars as pl
> 
> df = pl.DataFrame({'x':[1,2,3], 'y':[4,5,6]})
> df.plot.point(x='x', y='y')
> ```
> 
> How can I call the equivalent of doing:
> 
> ```python
> alt.Chart(df).mark_point().encode(
>     x=alt.X('x').title('foo'),
>     y='y'
> )
> ```
> 
> I see from the docstring there is a `ChannelX` type: ![image](https://private-user-images.githubusercontent.com/5186265/365446241-ed52a1df-6425-4fb8-a8a4-a86680c91b3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDc5ODYsIm5iZiI6MTcyNTgwNzY4NiwicGF0aCI6Ii81MTg2MjY1LzM2NTQ0NjI0MS1lZDUyYTFkZi02NDI1LTRmYjgtYThhNC1hODY2ODBjOTFiM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMTUwMTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI1MThjNjU1NGMwNDAzODE2NTgwMjU0OTc3YzU4NDMxNzcwZDRmZmM2NjY1ODk4Mzc5NzM0MjFiNmNiNDJkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Phzgs4HhSwEAfCn8h_Z0gra7oVxxf0Vm7vtn-JWh6HI)
> 
> But there is not such a thing as `pl.ChannelX()`.
> 
> ```python
> df.plot.point(
>     x=pl.ChannelX('x').title('foo'), 
>     y='y'
> )
> ```
> 
> > ```batchfile
> > AttributeError: module 'polars' has no attribute 'ChannelX'
> > ```
> 
> I realised I can do as such:
> 
> ```python
> import altair as alt
> 
> df.plot.point(
>     x=alt.X('x').title('foo'), 
>     y='y'
> )
> ```
> 
> But I'm not sure if this mixing is the intended approach.

@mattijn I'm not sure what it looks like in your IDE - but `ChannelX` is a type alias that should show something like this on hover: 

https://altair-viz.github.io/user_guide/generated/typing/altair.typing.ChannelX.html#altair.typing.ChannelX

IIRC there are some screenshots in here showing VSCode https://github.com/vega/altair/pull/3515

**Comment by MarcoGorelli** [comment]
thanks for your inputs - yup `alt.X('x', title='foo')` is how users could do it, though in https://github.com/pola-rs/polars/pull/18609 I'm suggesting adding it as an argument because of how common the desire to rename axis labels is

**Comment by mattijn** [comment]
@dangotbanned, I did attach a screenshot of how it looks like in my IDE, which is JupyterLab. As far as I understand, there is not such a thing as _on hover_ in the tooltip / signature help that I activated by pressing shift+tab upon entering the function.

@MarcoGorelli, my mental model is currently favouring something like, everything related to `x` do it in a `X` object, everything related to `y` in `Y` and everything related to `color`, do it in a `Color` object.

**Comment by dangotbanned** [comment]
> @dangotbanned, I did attach a screenshot of how it looks like in my IDE, which is JupyterLab. As far as I understand, there is not such a thing as _on hover_ in the tooltip / signature-help that I activated by pressing shift+tab upon entering the function.

Apologies @mattijn what I mean was that I wasn't sure what would be displayed if you hovered over the `ChannelX` symbol. 

From a quick search, it seems you might need something like this https://github.com/jupyter-lsp/jupyterlab-lsp 

Although @MarcoGorelli @binste if you have any experience with Jupyterlab - maybe you'd have a better suggestion?

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli, my mental model is currently favouring something like, everything related to x do it by using a X object, everything related to y by using a Y object and everything related to color, do it by using a Color object.

Yup I'd also prefer this, I'm just thinking about discoverability for people just using `df.plot` without necessarily knowing too much about Altair. An alternative to exposing `x_axis_title` / `y_axis_title` would be to just have some "plot customisation cheat sheet" in the Polars docs, showing some common tricks like `alt.X('x', title=...)` and then linking to the Altair docs if people want to take it further
 
It's hard to say where to draw the line 🤔 will sleep on it some more

**Comment by joelostblom** [comment]
I'm going to reopen this, since I think we should either support `configure_axisX(title='foo')` to have the intended effect or remove this option from the code base. Currently [our documentation indicates that this should work](https://altair-viz.github.io/user_guide/configuration.html#config-axis) which is confusing. I rarely use the `configure_*` methods myself, so I'm ok with removing it

Also [asked here on SO recently](https://stackoverflow.com/questions/78959850/change-x-label-after-chart-has-already-been-created).

**Comment by mattijn** [comment]
Yeah, 

One more thing to add, colors and color schemes is also something that people like to control often. Which could be done as such: 

```python
import polars as pl
import altair as alt

path = "https://raw.githubusercontent.com/pola-rs/polars/main/docs/data/iris.csv"
df = pl.read_csv(path)

df.plot.scatter(
    x='petal_length', 
    y='petal_width',
    color=alt.Color('sepal_length').scale(scheme="lightgreyred")
)
```
But with some more sleep and showers (🙌) we can come up with a more polars-centric approach.

**Comment by dangotbanned** [comment]
> I'm going to reopen this, since I think we should either support `configure_axisX(title='foo')` to have the intended effect or remove this option from the code base. Currently [our documentation indicates that this should work](https://altair-viz.github.io/user_guide/configuration.html#config-axis) which is confusing. I rarely use the `configure_*` methods myself, so I'm ok with removing it
> 
> Also [asked here on SO recently](https://stackoverflow.com/questions/78959850/change-x-label-after-chart-has-already-been-created).

@joelostblom These are the specs for each chart from https://github.com/vega/altair/issues/3582#issuecomment-2336665843

- [Open `Original` in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvtwCGADziUAGnhDFCAG0woQMCBBCTpIOjMIzVUGQFttyE2ZkBaAEaYAHAFZMANgDsnjAAnC7uMGwATH5sYGBBmC7hXjJ+LJ4+YIbc1jIATgDWqoQAngAOdiAaJNrGmFCQdCRIqCByqvCYGnQ6Ftwl5ToAjqQyRHDmxGg13MXtWF06LiB9ZRXDo+pmcFOGxgAklGCMmDk6YoSllMgA9NdTCDIAdAjjjKQuj3AQ14fHOXeYB5OKqETB3TyPCJsR4ARkeACtKNBlg5zJRMIRKKpTOZXB5vP5AiEwpForF4ok2MlUulMsgANqgCzIGHcJbIAAs0iZKAibJQnm5IGZLH5yB8kgAukYgA)
- [Open the `Fixed` in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO50AhoTl4QUOQFtMKEPMUBaAEaYAHAFZMANgDsJmAE59RmGwBMltmDC3M+p6bmWWE3MwEBkQNTkAJwBrZUIATwAHTWQQABsSTTDMKEg6EiRUEAAPZXhMNLotJW5iQjSUkBgICBBapMaAR1I5IjhFYjQs7niyrEqtfTaQBOStbt66hTgh0LCAEkowRkwIrTFCRMpkAHoToYQ5ADoEfsZSfSu4CBOtnYjzzEvdDMJMc5MV2cbCuAEYrgArSjQaY6OSUTCESjKOEGYxmKw2eyOFxuDxeHxsPwBIIhZAAbVASmQoO4U2QABYZFSUM46SgTMyQNSWOzkOZJABdaRAA)

I will admit it is odd that setting a default value for the axis results in its removal; but this is consistent with `vega-lite`

**Comment by mattijn** [comment]
Raised in VL https://github.com/vega/vega-lite/issues/9429

**Comment by joelostblom** [comment]
Thank you @mattijn, closing this one then.
