### ISSUE TITLE
Empty plot when column name contains a dot `.`

### ISSUE THREAD

**Issue by Julian-J-S** [vega/altair#3599]
### What happened?

When trying to plot a chart the chart is empty if my column name contains a dot `.`.

I am new to altair since the great polars integration and this seems like a bug to me because for all other plotting libraries this works just fine.

```python
alt.Chart(
    data=pl.DataFrame(
        {"x": [1, 2, 3], "y.1": [1, 4, 9]},
    )
).mark_line().encode(x="x", y="y.1")
```

## With dot in column name
![image](https://github.com/user-attachments/assets/ebc2edfd-ca4d-4075-ab83-aa00acf82466)

## Without dot
![image](https://github.com/user-attachments/assets/9c9e9b32-fe1c-4fca-ad46-97e2c0799181)

### What would you like to happen instead?

Normal plot to show

### Which version of Altair are you using?

5.4.1

**Comment by kgoodrick-uu** [comment]
Special characters (including periods) must be escaped in Altair column names. See [this section of the documentation](https://altair-viz.github.io/user_guide/encodings/index.html#escaping-special-characters-in-column-names) for more information and suggested workarounds.
