### ISSUE TITLE
Error when importing altair using Python 3.13

### ISSUE THREAD

**Issue by rikardn** [vega/altair#3620]
### What happened?

I am testing altair 5.4.1 with Python 3.13 rc2 and got the following error when trying to import:

```
$ python
Python 3.13.0rc2 (main, Oct  1 2024, 14:50:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import altair
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import altair
  File "/home/devel/pharmpy/.tox/py313/lib/python3.13/site-packages/altair/__init__.py", line 650, in <module>
    from altair.vegalite import *
  File "/home/devel/pharmpy/.tox/py313/lib/python3.13/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v5 import *
  File "/home/devel/pharmpy/.tox/py313/lib/python3.13/site-packages/altair/vegalite/v5/__init__.py", line 4, in <module>
    from .api import *
  File "/home/devel/pharmpy/.tox/py313/lib/python3.13/site-packages/altair/vegalite/v5/api.py", line 618, in <module>
    class _ConditionClosed(TypedDict, closed=True, total=False):  # type: ignore[call-arg]
    ...<6 lines>...
        value: Any
TypeError: _TypedDictMeta.__new__() got an unexpected keyword argument 'closed'
>>> 
```

### Which version of Altair are you using?

5.4.1

**Comment by dangotbanned** [comment]
@rikardn this will be fixed in the next release.
I think this PR would be all that's needed to fix this for you 
- https://github.com/vega/altair/pull/3593

More generally though, `altair` cannot be tested on `3.13` due issues upstream.
I would recommend following these for progress towards `3.13` support:
- https://github.com/vega/altair/issues/3587
- https://github.com/vega/altair/pull/3591

**Comment by rikardn** [comment]
Thanks @dangotbanned for taking the time to explain the situation.

**Comment by dangotbanned** [comment]
@rikardn we've just merged #3591, so I'm closing this as completed

If you still get the same error on `altair>=5.5.0` (*when it arrives*) please feel free to comment here and I'll reopen for you

**Comment by dangotbanned** [comment]
@rikardn we've just merged #3591, so I'm closing this as completed

If you still get the same error on `altair>=5.5.0` (*when it arrives*) please feel free to comment here and I'll reopen for you

**Comment by rikardn** [comment]
Thanks! I'll test the new version when available.

**Comment by jrieke** [comment]
Hey @dangotbanned, Johannes here from @streamlit. Do you have a rough idea of when 5.5.0 will be released? We're waiting for it to properly support Python 3.13 on our side (see https://github.com/streamlit/streamlit/pull/9635).

**Comment by dangotbanned** [comment]
> Hey @dangotbanned, Johannes here from [@streamlit](https://github.com/streamlit). Do you have a rough idea of when 5.5.0 will be released? We're waiting for it to properly support Python 3.13 on our side (see [streamlit/streamlit#9635](https://github.com/streamlit/streamlit/pull/9635)).

Hey @jrieke, I'm not too sure on a timeline right now so I've opened a discussion in:

- #3687

Apologies that we've been blocking for [streamlit/streamlit#9635](https://github.com/streamlit/streamlit/pull/9635) 😞
I know it can be frustrating waiting on upstream from (https://github.com/vega/altair/issues/3587)

I'm hopeful that we're not *too* far off from the next release

**Comment by jrieke** [comment]
Thanks so much, and no worries!

**Comment by balexandermunoz** [comment]
Still with the same issue here with the Python version 3.13.7 and altair 5.5.0
