### ISSUE TITLE
Adding `tooltip=` changes bar plot

### ISSUE THREAD

**Issue by MarcoGorelli** [vega/altair#3635]
### What happened?

```python
import polars as pl
import altair as alt
import numpy as np

rng = np.random.default_rng(1)

df =pl.DataFrame({
"value": rng.normal(0,1,1000)
})
```

Then, the following two plots differ:
```python
alt.Chart(df).mark_bar().encode(x=alt.X('value', bin=alt.BinParams(step=1)), y='count()', tooltip=['value'])
```
```python
alt.Chart(df).mark_bar().encode(x=alt.X('value', bin=alt.BinParams(step=1)), y='count()')
```

![Image](https://github.com/user-attachments/assets/b74e7529-9557-48e3-a1be-c98589315278)

### What would you like to happen instead?

I think I would expect that adding `tooltip=` would only affect the interactive behaviour, not what gets displayed

### Which version of Altair are you using?

5.4.1

**Comment by dangotbanned** [comment]
@MarcoGorelli I've put this together for you to play around with

```py
import numpy as np
import polars as pl

import altair as alt

rng = np.random.default_rng(1)
df = pl.DataFrame({"value": rng.normal(0, 1, 1000)})

# Shows all fields
tooltip_bar = True
# Only just discovered this option.
# Highlights that `"value"` isn't in scope
tooltip_bar = {"content": "data"}
# Default
tooltip_bar = alt.Undefined

tooltip_encoding = "count()"
tooltip_encoding = alt.Tooltip("value", bin=alt.Bin(step=1))
# Seems to be the one you want
tooltip_encoding = alt.Tooltip("value", bin=True)
# Default
# tooltip_encoding = alt.Undefined

# These are the same
x = alt.X("value", bin=alt.BinParams(step=1))
x = alt.X("value", bin=alt.Bin(step=1))

base = alt.Chart(df).mark_bar(tooltip=tooltip_bar)
chart = base.encode(x=x, y="count()", tooltip=tooltip_encoding)

chart
```

Most of these were new to me 😅, but I think this was what you were expecting to see

![Image](https://github.com/user-attachments/assets/e3c9c93a-8348-4845-b110-b4111779b400)


# Related
- https://altair-viz.github.io/user_guide/generated/channels/altair.Tooltip.html#altair.Tooltip
- https://altair-viz.github.io/user_guide/encodings/channel_options.html#href-tooltip-url
- https://vega.github.io/vega-lite/docs/tooltip.html

**Comment by dangotbanned** [comment]
Just seen this is from https://github.com/pola-rs/polars/issues/19159

I think it might be safer to make this change:

[**Current**](https://github.com/pola-rs/polars/blob/48bc09b544b3638472f64db3391d597bd5da720e/py-polars/polars/dataframe/plotting.py#L110-L111)
```py
_add_tooltip(encodings, **kwargs)
self._chart.mark_...().encode(**encodings, **kwargs).interactive()
```
**Proposed**
```py
self._chart.mark_...(tooltip=True).encode(**encodings, **kwargs).interactive()
```

The `.mark_...()` version has a lower precedence than `.encode()`; so you *may* be able to avoid [L33-L45](https://github.com/pola-rs/polars/blob/48bc09b544b3638472f64db3391d597bd5da720e/py-polars/polars/dataframe/plotting.py#L33-L45) entirely.

I'll continue this over there

**Comment by dangotbanned** [comment]
Fixed downstream in https://github.com/pola-rs/polars/pull/19213

Thanks @MarcoGorelli

**Comment by MarcoGorelli** [comment]
thanks @dangotbanned ! though even unrelated to Polars, it's unclear to me why adding `tooltip=['value']` in the example above changes the plot

**Comment by mattijn** [comment]
Per https://vega.github.io/vega-lite/docs/tooltip.html#channel 

> Encoding a field without an aggregate as a tooltip means that the field will be used to group aggregates by.
> 
> To avoid that the tooltips groups the data, add an aggregate to the tooltip encoding.

**Comment by MarcoGorelli** [comment]
Ah I should have spotted that - thanks 🙏
