### ISSUE TITLE
Update version Altair on pyodide

### ISSUE THREAD

**Issue by mattijn** [vega/altair#3642]
### What is your suggestion?

Update the altair version integrated within [pyodide](https://github.com/pyodide/pyodide), it is still on [5.3.0](https://pyodide.org/en/stable/usage/packages-in-pyodide.html), with the latest version of altair, the hard dependencies are drastically reduced, which is good for loading time.

### Related
- https://github.com/pyodide/pyodide/pull/4580
- https://github.com/pyodide/pyodide/issues/4918
- https://github.com/vega/altair/pull/3630#discussion_r1801090949
- [x] https://github.com/pyodide/pyodide/pull/5121
- [x] https://github.com/pyodide/pyodide/pull/5124
- [ ] [pyodide `0.27.0` Milestone](https://github.com/pyodide/pyodide/milestone/25)

**Comment by dangotbanned** [comment]
@joelostblom may need to do this, since they are listed as the recipe maintainer. 

I think this is the process to follow though:

- https://pyodide.org/en/stable/development/new-packages.html#upgrading-a-package

**Comment by joelostblom** [comment]
I ran the update steps locally and it seems to work fine. I can put up a PR and I'm happy to add anyone as a maintainer who wants to be on there. Before doing that however, I think we need someone to build a pyodide package for Narwhals since that is a new dependency that doesn't yet exist on pyodide?

**Comment by MarcoGorelli** [comment]
> I think we need someone to build a pyodide package for Narwhals since that is a new dependency that doesn't yet exist on pyodide?

on this 🏃

**Comment by joelostblom** [comment]
Super, thank you @MarcoGorelli ! I put up the altair PR referencing yours for Narwhals https://github.com/pyodide/pyodide/pull/5124

**Comment by joelostblom** [comment]
Closing this since https://github.com/pyodide/pyodide/pull/5124 was merged
