### ISSUE TITLE
pandas deprecation warning from within altair

### ISSUE THREAD

**Issue by jgunstone** [vega/altair#3648]
### What happened?

![Image](https://github.com/user-attachments/assets/2d103c85-9040-4c4e-a3ad-799f7c6f88a1)

### What would you like to happen instead?

no warnings

### Which version of Altair are you using?

5.1.0

**Comment by MarcoGorelli** [comment]
hey - this was removed a while ago (https://github.com/vega/altair/pull/3191/files), I think you may just need to upgrade your Altair version?

**Comment by jgunstone** [comment]
sorry - forgot that I had pinned to an old version because I was getting this error: 
https://github.com/vega/altair/issues/3649
