### ISSUE TITLE
Update `Chart.transform_filter()` to mirror `alt.when()`

### ISSUE THREAD

**Issue by dangotbanned** [vega/altair#3657]
### What is your suggestion?

The goal is simply to provide equivalent predicate parsing functionality, that is found in [`alt.when()`](https://altair-viz.github.io/user_guide/generated/api/altair.when.html#altair.when).

For example, this would be easy to port over:

```py
verbose_composition = (
    (alt.datum.Name == "Name_1")
    & (alt.datum.Color == "Green")
    & (alt.datum.Age == 25)
    & (alt.datum.StartDate == "2000-10-01")
)
when_verbose = alt.when(verbose_composition)
when_concise = alt.when(Name="Name_1", Color="Green", Age=25, StartDate="2000-10-01")
```

I was reading through [transform/filter](https://altair-viz.github.io/user_guide/transform/filter.html) and looking at the implementation:

<details><summary><code>.transform_filter()</code> implementation</summary>
<p>

https://github.com/vega/altair/blob/5a6f70dc193f7ed9c89e6cc22e95c9d885167939/altair/vegalite/v5/api.py#L2917-L2924

</p>
</details> 

AFAIK, the signature can be changed without impacting any existing code:

https://github.com/vega/altair/blob/5a6f70dc193f7ed9c89e6cc22e95c9d885167939/altair/vegalite/v5/api.py#L2888-L2898

- There are no checks on `filter` being in `**kwargs`
- The only *"valid"* keyword is `empty`
    - [`condition()`](https://github.com/vega/altair/blob/5a6f70dc193f7ed9c89e6cc22e95c9d885167939/altair/vegalite/v5/api.py#L1748) has already been safely updated in this way

I definitely want to do some more testing, but I can't see much that would be blocking closing the gap between the two:

https://github.com/vega/altair/blob/5a6f70dc193f7ed9c89e6cc22e95c9d885167939/altair/vegalite/v5/api.py#L1214-L1219

### Side note
#695 is referenced on that page, but I think it was resolved a while ago?

Also there are [references](https://altair-viz.github.io/user_guide/transform/filter.html#selection-predicates) to `selection()` which was deprecated in `5.0.0`

### Have you considered any alternative solutions?

- Leave `.transform_filter()` unchanged
- Accept `alt.When` (class) as `filter`
    - Would work by unwrapping `When._condition`
    - I'd prefer to add the expressiveness, without annotating `.transform_filter` with `When`
        - Seems less intuitive to me

**Comment by mattijn** [comment]
I think I support this request, but to be sure with an example:

- current (first example on https://altair-viz.github.io/user_guide/transform/filter.html
```python
import altair as alt
from altair import datum

from vega_datasets import data
pop = data.population.url

alt.Chart(pop).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(
    (datum.year == 2000) & (datum.sex == 1)
)
```

- with this feature request
```python
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(
    alt.when(year=2000, sex=1)
)
```

**Comment by dangotbanned** [comment]
> I think I support this request, but to be sure with an example:

Thanks for the quick response @mattijn 

Apologies, I wrote this up yesterday in a bit of a rush.

To clarify, below I've rewritten your comment with what I intended:

### Current (first example on [transform/filter](https://altair-viz.github.io/user_guide/transform/filter.html))

```py
import altair as alt
from altair import datum
from vega_datasets import data

pop = data.population.url

alt.Chart(pop).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(
    (datum.year == 2000) & (datum.sex == 1)
)
```

### With this feature request

```py
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(year=2000, sex=1)
```

### Alternative (2)
Your [example](https://github.com/vega/altair/issues/3657#issuecomment-2437105262) corresponds to what I mentioned at the end of the [description]( https://github.com/vega/altair/issues/3657#issue-2612299156)
> ### Have you considered any alternative solutions?
> 
> - ~~Leave `.transform_filter()` unchanged~~
> - **Accept `alt.When` (class) as `filter`**
>     - Would work by unwrapping `When._condition`
>     - I'd prefer to add the expressiveness, without annotating `.transform_filter` with `When`
>         - Seems less intuitive to me

```py
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_area().encode(
    x='age:O',
    y='people:Q',
).transform_filter(
    alt.when(year=2000, sex=1)
)
```

---

## Expanding on why I prefer not to include `When`
- Using `*args`, `**kwds` would correpond directly to [polars.DataFrame.filter](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.filter.html)
	- I feel there is a nice alignment then between:
		- `pl.when` -> `alt.when`
		- `pl.DataFrame.filter` -> `alt.Chart.transform_filter`
	- This makes it intuitive for users introduced to `altair` via `polars`
		- And in the future, maybe the reverse would also be true
- We would **not** need to add `&`, `|`, `~` operators to `When`
	- E.g. this isn't valid 
		- `alt.when(year=2000, sex=1) | datum.name == "john"`
- Syntactically, there are fewer concepts happening in the first - but it is not less expressive
	- *filter*-*predicates*-*constraints*
	- *filter*-*when*-*predicates*-*constraints*

**Comment by mattijn** [comment]
Ah, thanks for clarifying. Sounds like a good idea 👍

**Comment by jonmmease** [comment]
I'm in favor, we're not using the kwargs for anything currently, and using them for direct equality makes sense.

**Comment by dangotbanned** [comment]
Experimenting with this now, will publish a branch soon.

# Early findings
- Entirely removing `**kwargs`  breaks no tests/examples
    - Provided `empty` is added as named keyword-only argument
- [Ranged Dot Plot](https://altair-viz.github.io/gallery/ranged_dot_plot.html) is the only example which uses `filter` as a keyword
    - *Not* a deal-breaker
    - Will probably want to issue a deprecation warning and suggest passing as positional
        - Popping `filter` from [`**constraints`](https://altair-viz.github.io/user_guide/generated/api/altair.when.html#altair.when)
    - During the deprecation period, we'll have one edge case that *cannot* support the new syntax
        - `.transform_filter(filter=value)`, will still need to use
        - `.transform_filter(alt.datum["filter"] == value)`
