### ISSUE TITLE
Conda packages - Version mismatch

### ISSUE THREAD

**Issue by ale-dg** [vega/altair#3686]
### What happened?

Hi all,

Hope everything is going well. A quick report: I installed Altair from the Conda-forge channel in a new Conda environment and got an error regarding the incompatibility of versions between vegafusion and vegafusion-python-embed (the first is 2.0.0rc1 and the second is 1.6.9). I did a reinstall and indeed both packages are being retrieved as so: 

![Image](https://github.com/user-attachments/assets/74580f83-dce3-4d01-8bb4-92e0263d75e9)

I checked in the site and indeed the package for vegafusion-python-embed has not been updated. Is there a newer version which could be uploaded, please? I know the workaround is to downgrade vegafusion to 1.6.9, although I guess there is also a newer version of the python-embed since the first one is also available.

https://anaconda.org/conda-forge/vegafusion/files

https://anaconda.org/conda-forge/vegafusion-python-embed/files

Thanks!

Best

### What would you like to happen instead?

Both packages in the most recent version for avoiding incompatibility

**Comment by joelostblom** [comment]
Thanks for the report! The PR to constrain the versions correctly was just merged here https://github.com/conda-forge/altair-feedstock/pull/58. If you try again, the compatible versions should now be installed automatically. When the next release of Altair is out, we will update the conda package to install vegafusion 2.0.

**Comment by ale-dg** [comment]
Hi @joelostblom 

Thanks for the reply! I have checked and it's still retrieving the 2.0.0rc1 version. Would it be possible that is an issue with the osx-arm version?

Thanks!

Best

![Image](https://github.com/user-attachments/assets/c5c88064-58ab-4e59-90f0-dee69a5f40b0)

**Comment by joelostblom** [comment]
Thanks @ale-dg , I can reproduce on my linux machine so I don't think it is osx-arm specific. I tried to restrict the vegafusion version further in https://github.com/conda-forge/altair-feedstock/pull/60. Once the automatic build of a new package is done (should be a few hours), there will be a new package here https://anaconda.org/conda-forge/altair-all/files with the `_3` suffix. Then we can try to install again.

**Comment by joelostblom** [comment]
I just tried and the latest changes seem to have restricted altair-all 5.4.1 to install vegafusion 1.6.9 as it should. There was also just a release of altair 5.5.0 and the corresponding conda package altair-all 5.5.0 is installing vegafusion 2.0.0 as expected.
