### ISSUE TITLE
simplify deprecation message for altair.themes?

### ISSUE THREAD

**Issue by mattijn** [vega/altair#3694]
### What is your suggestion?

In the deprecation message of altair.themes we see currently among other things:
https://github.com/vega/altair/blob/c41e29e0bfa9e34d942635e574b2accfd9f2de0d/altair/__init__.py#L681

```python
    # Updated
    @alt.theme.register('theme_name', enable=True)
    def custom_theme() -> alt.theme.ThemeConfig:
        return {'height': 400, 'width': 700}
```

I'm wondering if we really need to add ` -> alt.theme.ThemeConfig` when defining this function. Within a Jupyter Notebook I really rarely see this approach being utilised and in combination with the usage of a `@` decorator to register the theme, also something I really rarely see people doing a Jupyter Notebook, this deprecation message feels a bit overwhelming to me.

### Have you considered any alternative solutions?

@dangotbanned, if it's not too much trouble, I prefer making one change at a time as a user. Can we just do this?
```python
# Updated
@alt.theme.register('theme_name', enable=True)
def custom_theme():
    return {'height': 400, 'width': 700}
```

**Comment by dangotbanned** [comment]
@mattijn I do understand the concern.

One thing I'd add though is that adding the annotation is what **provides** the static typing **feedback**.

So even if you don't understand typing, if you copy and paste the code - your IDE can let you know if something is wrong. 

### Original

```py
import altair as alt

@alt.theme.register('theme_name', enable=True)
def custom_theme() -> alt.theme.ThemeConfig:
    return {'height': 400, 'width': 700}
```

### Alternatives

If we just want to shorten it we could say:

```py
from altair import theme

@theme.register('theme_name', enable=True)
def custom_theme() -> theme.ThemeConfig:
    return {'height': 400, 'width': 700}
```

or

```py
from altair.theme import register, ThemeConfig

@register('theme_name', enable=True)
def custom_theme() -> ThemeConfig:
    return {'height': 400, 'width': 700}
```

Both of these would be a shorter message - while not limiting the benefits of the original

**Comment by mattijn** [comment]
I'm in JupyterLab and I don't get any feedback🤷‍♂️

**Comment by dangotbanned** [comment]
> I'm in JupyterLab and I don't get any feedback🤷‍♂️

I think we'll need to figure out a good suggestion for that case as part of https://github.com/vega/altair/issues/3645

> ### Non-typing users
> 
> * Class-syntax is required for completions
> * Still likely an improvement over using a `dict`
> * Point to resources on how they can get the full benefits
>   * `ipython`/**`jupyter`**  
>     * **Language servers/plugins/extensions**
>   * IDE
>     * [typing-typing-related-tools](https://typing.readthedocs.io/en/latest/index.html#typing-related-tools)
>     * I'd probably call out [VSCode](https://code.visualstudio.com/) w/ [`pylance`](https://github.com/microsoft/pylance-release) as a common case

**Comment by mattijn** [comment]
Can we do this?

```
import altair as alt

@alt.theme.register('theme_name', enable=True)
def custom_theme():
    return alt.theme.ThemeConfig(
        {'height': 400, 'width': 700}
    )
```

Still a single `import altair as alt` import and also just a dictionary as input of the `alt.theme.ThemeConfig`, an object that you have when facing this message.

**Comment by dangotbanned** [comment]
https://github.com/vega/altair/issues/3694#issuecomment-2495461935

Yeah @mattijn that works for me

**Comment by mattijn** [comment]
Once JupyterLab and Jupyter Notebook (classic) have proper language service support, these types of changes will be easier to implement. However, we're not there yet. Thanks for helping to find an intermediate solution!
