### ISSUE TITLE
Accommodate named datasets

### ISSUE THREAD

**Issue by jakevdp** [vega/altair#575]
With the bump to vega-lite 2.3 (#571), we can now think about how to use named datasets within Altair. cc/ @ellisonbg

**Comment by dangotbanned** [comment]
Closing as support for named datasets is present, and is currently used for hashing

https://github.com/vega/altair/blob/1208c5d79e7ff0c10c5cd60bc21462f1be2073c9/altair/vegalite/v5/api.py#L206-L258
